repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: go-mod-tidy
        name: go mod tidy
        entry: bash -c 'cd dockerproxy && go mod tidy'
        language: system
        files: \.go$
        pass_filenames: false

      - id: go-fmt
        name: go fmt
        entry: gofmt
        args: [-w]
        language: system
        files: \.go$
