#!/bin/bash

set -e

trap 'echo "Received premature SIGUSR1"' SIGUSR1

if [[ -d "docker-entrypoint.d" ]]
then
echo "Running docker-entrypoint.d files"
/bin/run-parts docker-entrypoint.d
fi

echo "Running $@"

exec "$@"