#!/bin/bash

set -e

DATA_DIR=${DATA_DIR:-/data}
NIX_DIR=${DATA_DIR}/nix
ROOT_HOME_DIR=${DATA_DIR}/root

# Create the rsync target directory for housing build source
mkdir -p ${DATA_DIR}/source

# Create a persistent root home directory for storing Nix-related directories
mkdir -p $ROOT_HOME_DIR

# Create the persistent Nix store directory
mkdir -p $NIX_DIR

if [ -z "$(ls -A $NIX_DIR)" ]; then
  echo "The persistent nix store is empty, so bootstrap it from the image."
  rsync -av /nix/ $NIX_DIR
fi

if [ -z "$(ls -A $ROOT_HOME_DIR)" ]; then
  echo "The persistent root home directory is empty, so bootstrap it from the image."
  rsync -av /root/ $ROOT_HOME_DIR
fi

echo "Bind-mounting persistent nix store to /nix."
mount --bind $NIX_DIR /nix

echo "Bind-mounting persistent root home directory to /root."
mount --bind $ROOT_HOME_DIR /root